### ISSUE TITLE
DeltaTMRCA

### ISSUE THREAD

**Issue by trvrb** [evogytis/fluB#40]
I may be missing something obvious, but is &Delta;TMRCA representing "difference" or delta appropriately?  If segments A and B are have differences in TMRCA that are similar to differences in TMRCA within A and within B, then &Delta;TMRCA is near 1.  If A and B differences are bigger than &Delta;TMRCA approaches 0.  This seems completely backwards, doesn't it?  Can we flip the sign, so that completely similar is 0 and completely different is 1.

This looks like what Figure S14 (`deltaTMRCAtrees`) is doing?  Here PB1-PB2 is low rather than high like in Figure 8 (`deltaTMRCA`).

**Comment by evogytis** [comment]
I can totally see how this might be confusing. I intended ΔTMRCA to be the actual difference in TMRCAs between two trees, which we then normalize by ΔTMRCA within each tree. I'll change the equations in Methods to reflect this, so that instead of f (A_i, B_i) in the equation it will say Δ(bar)TMRCA (A_i, B_i).
As for the scale I was considering flipping the normalization equation, so that you can interpret the normalized measure as the factor by which between tree measure is bigger than the within tree measure. This would turn most comparisons to 10 (2 \* between comparisons is 10 times bigger than the sum of within comparisons) and PB1-PB2-HA to something quite close to 1.
Figure S14 has low values because differences in TMRCAs between pairs of tips in PB1 and PB2 trees on average do not exceed 2 years. I'll try making the nomenclature more consistent.

**Comment by trvrb** [comment]
I like it, but what about referring to normalized version as &Delta;<sub>TMRCA</sub> and the unnormalized version (used in the right side of eq 1) as &delta;<sub>TMRCA</sub>?  You can still label your plots as you have "normalized &Delta;<sub>TMRCA</sub>".

**Comment by trvrb** [comment]
Awesome!
