### ISSUE TITLE
confused?

### ISSUE THREAD

**Issue by BEAST-Community** [evogytis/fluB#42]
I find that your github of data file have 473 genome sequences for primary data, and 1602 genome sequences for secondary data, but your paper has mentioned 452 and 1603, respectively, and I do not know why?

**Comment by evogytis** [comment]
You can cross reference strain names in the GISAID acknowledgment table with those in the XMLs to see which sequences were used.

**Comment by BEAST-Community** [comment]
thanks for your reply. I find that you keep one genome per strain for primary data. And for secondary data, you added three genomes, one sampled at 2008, two are sampled at 1940, plus 1602, the total is 1605, but I don’t find the 1605 data for beast and other analysis, just did ml trees, is that right?

**Comment by evogytis** [comment]
Did you read the Materials and Methods section of the original paper? https://academic.oup.com/mbe/article/32/1/162/2925578

**Comment by BEAST-Community** [comment]
how to import the genome information into figtree?
<img width="199" alt="image" src="https://user-images.githubusercontent.com/38597277/55282993-3f5b0500-538b-11e9-988c-98bca4b75050.png">

**Comment by BEAST-Community** [comment]
why exclude sequences that are sampled before 1980s, 

BTW, the following color scheme of the genome information is determined by yourself or automatically by figure tree, thanks.
<img width="172" alt="image" src="https://user-images.githubusercontent.com/38597277/55283113-23a52e00-538e-11e9-9470-fd539e951098.png">

**Comment by BEAST-Community** [comment]
<img width="127" alt="image" src="https://user-images.githubusercontent.com/38597277/55283146-f0af6a00-538e-11e9-9902-60ad086f37f1.png">

**Comment by evogytis** [comment]
Read the literature on influenza B viruses. Questions about FigTree are exceedingly irrelevant to this project, please read the manuals: http://beast.community/index.html or ask your questions in the relevant groups: https://groups.google.com/forum/#!forum/figtree-announce

While I have your attention can I ask that you finish editing your fork of my website (https://github.com/lixingguang/lixingguang.github.io) or delete it? It is up online and gives the impression that it's by me. It is against GitHub user's terms and conditions to impersonate someone. I would also like to ask you to stop raising irrelevant issues on my repositories - it could be construed as harassment and incidentally is also against GitHub user's terms and conditions.

**Comment by ghost** [comment]
@what kind of things should I ask?
who impersonate whom?
what is real open science?

**Comment by ghost** [comment]
@ I just want to learn how to setup my website from you, and I forked from you, and have no time to change the information, actually,  I forked from many person, not just you. and just want to learn how to set up my own website.

**Comment by evogytis** [comment]
By forking my website you have copied all of my information too, which is accessible online. None of the other websites you have forked appear to belong to individuals. I don't have any issues with people using my website as a foundation for theirs, what I do have issue with is when the repository has been forked for half a year without any work done on it, such that it is out-dated and still looks like mine. You are more than welcome to fork the original website from minimal mistakes (https://github.com/academicpages/academicpages.github.io) like I did if you intend to have a website of your own or simply finish editing the one you forked from me. On the topic of impersonation you have also used logotypes that were not created by you, including one created by Trevor Bedford and another used by the real BEAST community. I suggest you reconsider your course of action before you are reported to GitHub.
Your behaviour has little to do with open science, because as far as I can tell everyone in the field has tried being helpful to you by pointing you towards publicly available resources where you can read and learn about the subjects of your questions. You have instead attempted to coerce everyone into doing your work for you, _e.g._ https://github.com/jameshadfield/phandangoExampleData/issues/1.

**Comment by ghost** [comment]
i just want to ask questions about your paper of flu B, please focus on this. I really do not do know how long the fork time are out of date. I just want to someone for help, in your world, is that mean coerce?
In my world, it is not.

**Comment by evogytis** [comment]
For the first few times that you've asked for help people have gone out of their way to help, but as the questions piled on it has became very clear that you have not bothered to read about any of the subjects in greater detail whatsoever and refuse to read about them when you're pointed towards resources that would be helpful to you. So if you haven't bothered why should we?

**Comment by ghost** [comment]
Thanks for your tips. I will take a second when I ask someone for help, but I am really not good at coding, so when I use the scripts that someone posted to analysis my data, there are always occur some error, even I read the resource, and can not solve it, so please understand it, I really want to be your friend, and want to learn cool things from many people like you.

**Comment by ghost** [comment]
I recently also focus on fluB data analysis, and have no idea how to analysis it, so I find that you published two papers focused on this, so I want to see if I can have new idea from your research, and found that it is confused to name sequences from fluB either vic or yam for each segment, for HA, this may be reasonable, but for some of other segments, I find that what you mentioned of two clades vic and yam, they can not separate with each other, so in my opinion, based on this, I think your methods may not be appropriate, what do you think, my friends?
